version: '3.8'

services:
  autenticacion:
    build:
      context: ./autenticacion
    ports:
      - "3001:3001"
    depends_on:
      - backend  # Asegura que el backend esté disponible primero

  carrito:
    build:
      context: ./carrito
    ports:
      - "3003:3003"
    depends_on:
      - backend

  productos:
    build:
      context: ./productos
    ports:
      - "3002:3002"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
